### Login
# @name login
POST {{host}}/auth/login/email
content-type: application/json

{
  "email": "jame@ex1app.com",
	"password": "12345678Test"
}
###

@myAccessToken = {{login.response.body.accessToken}}

### Create products
POST {{host}}/products
Content-Type: application/json
authorization: Bearer {{myAccessToken}}

{ 

    "name": "Product  5",
    "price": 100,
    "image": "https://example.com/avatar.jpg",
    "description": "This is a product description"
}

### Get All Products
GET {{host}}/products

### Get Product By Id
GET {{host}}/products/18c78713-de5f-4cda-a74d-9fc9aafeeb9e