### Login
# @name login
POST {{host}}/auth/login
content-type: application/json

{
  "username": "user1",
	"password": "12345678"
}
###

@myAccessToken = {{login.response.body.accessToken}}

### Create products
POST {{host}}/products
Content-Type: application/json
authorization: Bearer {{myAccessToken}}

{ 

    "name": "Product  5",
    "price": 100,
    "image": "https://example.com/avatar.jpg",
    "description": "This is a product description"
}

### Get All Products
GET {{host}}/products
authorization: Bearer {{myAccessToken}}

### Get Product By Id
GET {{host}}/products/99aad0e1-ba4c-4466-886a-63c857096107
authorization: Bearer {{myAccessToken}}
